settings:
  bullet: '*'
  rule: '-'
  fences: true
  listItemIndent: one

plugins:
  # Check that markdown is consistent.
  - remark-gfm
  - remark-preset-lint-consistent

  - remark-preset-lint-recommended
  - remark-preset-lint-markdown-style-guide

  - - remark-lint-list-item-indent
    - space

  - - remark-lint-ordered-list-marker-value
    - ordered

  - remark-lint-strikethrough-marker
  - remark-lint-checkbox-content-indent

  - - remark-lint-checkbox-character-style
    - {checked: 'x', unchecked: ' '}

  - remark-lint-linebreak-style

  - - remark-lint-unordered-list-marker-style
    - '*'

  - - remark-lint-no-missing-blank-lines
    - exceptTightLists: true

  - - remark-lint-link-title-style
    - false

  - remark-lint-first-heading-level
  - remark-lint-no-heading-indent
  - remark-lint-no-heading-like-paragraph
  - remark-lint-no-duplicate-headings-in-section
  - remark-lint-no-paragraph-content-indent
  - remark-stringify
  - - remark-toc
    - heading: contents

  - - remark-lint-maximum-line-length
    - false

  - - remark-lint-list-item-spacing
    - false
